export const DEFAULT_WEIGHTS = {
  renta_norm: 0.25,
  densidad_norm: 0.0,
  jovenes_norm: 0.25,
  mayores_norm: 0.25,
  actividad_norm: 0.0,
  uso_comercial_norm: 0.0,
  antiguedad_norm: 0.0,
};

export const VARIABLES = [
  {
    key: 'renta_norm',
    label: 'Renta',
    description: 'Capacidad adquisitiva media de la sección censal.',
    enabled: true,
    absKey: 'renta_abs',
    absLabel: 'Renta media',
    absFormat: (value) => `${Number(value || 0).toLocaleString('es-ES')} €`,
  },
  {
    key: 'densidad_norm',
    label: 'Densidad',
    description: 'Sin datos disponibles.',
    enabled: false,
    absKey: 'poblacion_abs',
    absLabel: 'Habitantes',
    absFormat: (value) => `${Number(value || 0).toLocaleString('es-ES')} hab.`,
  },
  {
    key: 'jovenes_norm',
    label: 'Jóvenes',
    description: 'Peso relativo de población menor de 20 años.',
    enabled: true,
    absKey: 'jovenes_norm',
    absLabel: '% Jóvenes',
    absFormat: (value) => Number(value || 0).toFixed(2),
  },
  {
    key: 'mayores_norm',
    label: 'Mayores',
    description: 'Peso relativo de población mayor de 64 años.',
    enabled: true,
    absKey: 'mayores_norm',
    absLabel: '% Mayores',
    absFormat: (value) => Number(value || 0).toFixed(2),
  },
  {
    key: 'actividad_norm',
    label: 'Actividad',
    description: 'Sin datos disponibles.',
    enabled: false,
    absKey: 'actividad_abs',
    absLabel: 'Establecimientos',
    absFormat: (value) => `${Number(value || 0).toLocaleString('es-ES')} estab.`,
  },
  {
    key: 'uso_comercial_norm',
    label: 'Uso comercial',
    description: 'Sin datos disponibles.',
    enabled: false,
    absKey: 'uso_comercial_norm',
    absLabel: 'Índice comercial',
    absFormat: (value) => Number(value || 0).toFixed(2),
  },
  {
    key: 'antiguedad_norm',
    label: 'Antigüedad',
    description: 'Sin datos disponibles.',
    enabled: false,
    absKey: 'antiguedad_norm',
    absLabel: 'Índice antigüedad',
    absFormat: (value) => Number(value || 0).toFixed(2),
  },
];